### ISSUE TITLE
.gf_progressbar_wrapper needs extra top margin when .gform_heading precedes it

### ISSUE THREAD

**Issue by cjg89** [UCF/Athena-GravityForms-Plugin#8]
The progress bar wrapper element on multipage forms (`.gf_progressbar_wrapper`) doesn't account for a form title/subtitle preceding it, and has no vertical space separating them.  See screenshot.

We could add something like:
```scss
.gform_heading + .gf_progressbar_wrapper {
  margin-top: 1.25rem;
}
```
to fix.

![screen shot 2018-10-12 at 2 16 10 pm](https://user-images.githubusercontent.com/1649216/46886887-2933a980-ce2a-11e8-9626-2ee91db5e5fd.png)
