### ISSUE TITLE
List input add/remove buttons are too small

### ISSUE THREAD

**Issue by cjg89** [UCF/Athena-GravityForms-Plugin#9]
See screenshot--these images must have been modified in a recent update of GravityForms.  They are now about 5px wide, which is very difficult to see and click.

Something like
```scss
.gfield_list_icons {

  ...

  .add_list_item,
  .remove_list_item {
    display: block;
    width: 1rem;
  }
}
```
seems to help.  May want to look into increasing the icon size a bit at -xs and -sm for easier touch-based controls.

![screen shot 2018-10-12 at 2 24 06 pm](https://user-images.githubusercontent.com/1649216/46887292-3c934480-ce2b-11e8-9e3d-ee8c8d22a13a.png)
